/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author João P. Arquim
 */
public class TelaTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form TelaTriangulo
     */
    public TelaTriangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSegmA = new javax.swing.JLabel();
        lblSegmB = new javax.swing.JLabel();
        lblSegmC = new javax.swing.JLabel();
        lblTriangulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        sldLadoA = new javax.swing.JSlider();
        sldLadoB = new javax.swing.JSlider();
        sldLadoC = new javax.swing.JSlider();
        lblResultA = new javax.swing.JLabel();
        lblResultB = new javax.swing.JLabel();
        lblResultC = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSegmA.setText("Segmento A:");

        lblSegmB.setText("Segmento B:");

        lblSegmC.setText("Segmento C:");

        lblTriangulo.setBackground(new java.awt.Color(0, 0, 153));
        lblTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTriangulo.setForeground(new java.awt.Color(0, 0, 153));
        lblTriangulo.setText("Formam um Triangulo");

        lblNome.setBackground(new java.awt.Color(204, 0, 0));
        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 0, 0));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("        ...");

        sldLadoA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldLadoAStateChanged(evt);
            }
        });

        sldLadoB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldLadoBStateChanged(evt);
            }
        });

        sldLadoC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldLadoCStateChanged(evt);
            }
        });

        lblResultA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResultA.setText("0");

        lblResultB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResultB.setText("0");

        lblResultC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResultC.setText("0");

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/triangulo-reto (2).png"))); // NOI18N

        btnVerificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sldLadoC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSegmA)
                                        .addComponent(lblSegmB, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sldLadoA, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(sldLadoB, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                .addComponent(lblTriangulo))
                            .addComponent(lblSegmC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultB)
                            .addComponent(lblResultA)
                            .addComponent(lblResultC)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnVerificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(lblImagem)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSegmA)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sldLadoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblResultA)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldLadoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSegmB)
                    .addComponent(lblResultB))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblImagem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSegmC)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sldLadoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblResultC)))
                        .addGap(18, 18, 18)
                        .addComponent(btnVerificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(lblTriangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome)
                        .addContainerGap(41, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        //pegando os valores no slider inserido pelo usuário
        int ladoa = sldLadoA.getValue();
        int ladob = sldLadoB.getValue();
        int ladoc = sldLadoC.getValue();
        
        //atribuição das strings com os nomes dos triangulos
        String nomeeq = "Equilátero";
        String nomeis = "Isósceles";
        String nomeesc = "Escaleno";
        
        //estrutura com as condições de cada tipo de triangulo
        if(ladoa == ladob && ladob == ladoc && ladoa == ladoc){//triangulo equilátero
            lblNome.setText(nomeeq);
        }else if(ladoa != ladob && ladob != ladoc && ladoc != ladoa){//trinagulo escaleno
            lblNome.setText(nomeesc);
        }else{
            lblNome.setText(nomeis);//triangulo isósceles
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    //criei três "states changed" para os sliders
    //com esse evento consigo mudar os valores dos labels
    private void sldLadoAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldLadoAStateChanged
        // TODO add your handling code here:
        //Lado A
        lblResultA.setText(String.valueOf(sldLadoA.getValue()));
    }//GEN-LAST:event_sldLadoAStateChanged

    private void sldLadoBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldLadoBStateChanged
        // TODO add your handling code here:
        //Lado B
        lblResultB.setText(String.valueOf(sldLadoB.getValue()));
    }//GEN-LAST:event_sldLadoBStateChanged

    private void sldLadoCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldLadoCStateChanged
        // TODO add your handling code here:
        //Lado C
        lblResultC.setText(String.valueOf(sldLadoC.getValue()));
    }//GEN-LAST:event_sldLadoCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblResultA;
    private javax.swing.JLabel lblResultB;
    private javax.swing.JLabel lblResultC;
    private javax.swing.JLabel lblSegmA;
    private javax.swing.JLabel lblSegmB;
    private javax.swing.JLabel lblSegmC;
    private javax.swing.JLabel lblTriangulo;
    private javax.swing.JSlider sldLadoA;
    private javax.swing.JSlider sldLadoB;
    private javax.swing.JSlider sldLadoC;
    // End of variables declaration//GEN-END:variables
}
